services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myapp-container
    networks:
      - mynetwork
    depends_on:
      postgres:
        condition: service_healthy
    command: python test_app.py
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - mynetwork
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "mydb"]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 10s
networks:
  mynetwork:
    driver: bridge
volumes:
  postgres_data: